# Generated by Django 5.1.3 on 2024-12-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('room', 'غرفة'), ('apartment', 'شقة'), ('studio', 'استوديو'), ('villa', 'فيلا'), ('resort', 'منتجع')], max_length=20)),
                ('rooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
